### ISSUE TITLE
Refactor denoise.py to utilise existing dependencies

### ISSUE THREAD

**Issue by aidanjgriffiths** [OnTrack-UG-Squad/speaker-verification#25]
Refactor out `denoise.py` and encapsulate the function into either existing dependencies like `librosa` and or `wave` instead of relying on the custom function. This should be extended to be utilized before the `deep-speaker` sub-module is called in the `enroll` and `validate` workflows are called.

Some sort of test to gauge the effectiveness of this `denoise` process will be needed in order to justify its runtime costs in this project.

**Comment by aidanjgriffiths** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor denoise.py to utilise existing dependencies](https://trello.com/c/0ODNWiSd/126-refactor-denoisepy-to-utilise-existing-dependencies)

**Comment by aidanjgriffiths** [comment]
It seems that [sox](https://pypi.org/project/sox/) is quite a popular tool for dealing with audio file cleaning.

**Comment by sometheasiekswx** [comment]
Current denoiser is based on this code: https://github.com/JelixLi/ID_Speech_Recognition/blob/073f7b6c49f682b04d8a648c09f9079c97c92ec1/enhance_speach.py

**Comment by sometheasiekswx** [comment]
I think it's best to use a premade package like this noisereduce (https://pypi.org/project/noisereduce/) so we don't have to maintain the code.
