### ISSUE TITLE
Convert Speaker Verification To RESTful Service 

### ISSUE THREAD

**Issue by notkurt** [OnTrack-UG-Squad/speaker-verification#26]
### Brief

As speaker verification matures, the direction of its finial implementation needs to be considered. This would allow for the project to be a continually evolving extension of Doubtfire. This direction will serve as an effective way to guide next steps on how the project will proceed. 

### Proposed Technical Stack

- Entire development and production environment, and their dependancies are housed within [Docker](https://www.docker.com/) using [Docker Compose](https://docs.docker.com/compose/). 
- [Django](https://www.djangoproject.com/) serves as the web framework for the project. This suits the project due to Python being the language used for the current project. 
- [Gunicorn](https://gunicorn.org/) serving as the WSGI. 
- [Celery](https://docs.celeryproject.org/en/stable/) for task queuing. 
- [Redis](https://redis.io/) for message brokering with the tasks. 
- [PostgreSQL](https://www.postgresql.org/) for the database. 
- [Nginx](https://www.nginx.com/) for the web server. 

### Commentary 

This technical stack is based on personal preference, so it would be great to get some feedback. By doing it this way we will achieve the following: 

- Removing the need to write SQL Queries. Automatically manage database migrations as the project evolves. Develop models in an easy to read format. 

![Screen Shot 2021-03-15 at 4 38 04 pm](https://user-images.githubusercontent.com/64142230/111108385-e2bf7780-85ac-11eb-87fa-83a0ba16346c.png)

_Screenshot of a Django model_

- Unified development environment. Setup production or dev environment by setting a few environment variables and running `docker-compose -f docker-compose.yml up -d --build`
- Make use of established Django frameworks such as the Django Rest Framework. 
- Easily develop tests. 
- Already has a backend admin panel, incase you needed to easily view / edit data in the DB. 

![Screen Shot 2021-03-15 at 4 29 39 pm](https://user-images.githubusercontent.com/64142230/111107859-c66f0b00-85ab-11eb-924f-3db2c30a44cd.png)

_Screenshot of a Django Admin Panel_

The direction the RESTFul implementation of this project would take heavily depends on the project's final intentions. For example, if this project were to evolve in a larger contract cheating prevention platform, then building a proper web service might be a good direction to take the project.

It would probably take 2-3 hours to get this all setup and working properly, with some basic documentation. 

Looking forward to hearing your thoughts.

**Comment by notkurt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Investigating the RESTFul implementation of speaker-verification.](https://trello.com/c/df6KMjTj/125-investigating-the-restful-implementation-of-speaker-verification)

**Comment by aidanjgriffiths** [comment]
Do you think we could refactor the current `speaker-verification` package so that we could have a standalone python package and a different RESTful API that wraps around the core package in order to keep both use cases viable?

eg. swap out `sqlite3` for `postgreSQL` in the current package then have 2 projects which we can version to maintain compatability between the 2 repositories.

**Comment by macite** [comment]
This sounds like a good idea to me. You could wrap the CLI version in a RESTful API... no need to have it nested within the API code. Then you can write the API in whatever language you want, no need to be python there, other languages may be better options. Then that code calls the speaker-verification code via system calls.

**Comment by notkurt** [comment]
My background is heavily weighted in building Django projects, so I am probably a little biased in this regard. General discussions have pointed to having this as a seperate repository. I am definitely open to discussing other implementations for the API service, if we don't believe Django would be a suitable fit - and am willing to take charge of this part of the project. However if we don't go with Django, it might be best to be led by someone who has some strong experience with the respective framework. I'm all for upskilling, however I wouldn't feel comfortable architecting something in something going into production that I am only just learning.

**Comment by notkurt** [comment]
![SpeakerVer (1)](https://user-images.githubusercontent.com/64142230/111945167-49a0db80-8b2d-11eb-8e9e-9605d9f27857.png)

Attached is a proposed diagram for the system setup for the API.

**Comment by notkurt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Formal project planning for RESTful implementation of speaker-verification](https://trello.com/c/JTay1DJX/133-formal-project-planning-for-restful-implementation-of-speaker-verification)

**Comment by aidanjgriffiths** [comment]
Closing due to work being available [here](https://github.com/OnTrack-UG-Squad/speaker-verification-api).
