### ISSUE TITLE
Create CI code coverage badge

### ISSUE THREAD

**Issue by aidanjgriffiths** [OnTrack-UG-Squad/speaker-verification#28]
Create a coverage badge in the `README.md` that links to the coverage of tests run in the CI.

- [ ] Create a mechanism in the existing `python-ci.yml` file that takes the coverage value from passing tests.
- [ ]  Create a coverage badge that displays the coverage value in `README.md`.

[See actions coverage mechanism](https://docs.codeclimate.com/docs/github-actions-test-coverage)

**Comment by aidanjgriffiths** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create CI code coverage badge](https://trello.com/c/LyV40Vzh/129-create-ci-code-coverage-badge)

**Comment by aidanjgriffiths** [comment]
After doing a bit of [research](https://itnext.io/github-actions-code-coverage-without-third-parties-f1299747064d) it doesn't look like this is supported through github actions and we need to involve third party cloud component which is out of the question in my opinion.

@notkurt feel free to close issue if you feel similarly.

**Comment by notkurt** [comment]
Hey @aidanjgriffiths - I did some similar research and it seems as if you are on the money for that, it will require a cloud component, or I did see there was a Python package to facilitate this also - however I don't believe it's worth adding additional dependancies for this sole usecase.

Closing the issue.
