### ISSUE TITLE
Add git tags to previous trimesters work

### ISSUE THREAD

**Issue by aidanjgriffiths** [OnTrack-UG-Squad/speaker-verification#30]
Add tags to end of last trimester as some version which will be built upon this trimester for historical records. This will establish the point where our teams contribution starts from last year.

**Comment by namvnn** [comment]
Can you please elaborate more about this issue? Where should the tags be applied?

**Comment by aidanjgriffiths** [comment]
@nnfunny I should have made this more detailed but I just wanted to get a heap of issues out so everyone had something to do. This was just intended for me to evaluate the the previous commits in the repo in order to figure out how to best version the code with [git tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging). 

I've done this with [`v0.1`](https://github.com/OnTrack-UG-Squad/speaker-verification/releases/tag/v0.1) by using [semantic versioning conventions](https://semver.org/) so we can close this issue since the work has been done.
